apiVersion: v1
kind: Service
metadata:
  name: devops-app-svc
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 3000        
      targetPort: 3000  
      nodePort: 30080   
